2017-05-12 18:00:50:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-12 18:28:35:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-12 18:31:07:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-12 19:36:44:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-13 04:09:52:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-13 05:02:10:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-15 10:39:35:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-15 14:52:38:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-15 14:57:40:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-15 14:58:00:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-15 15:03:15:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-15 15:24:53:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 41, in fetchWriterTitle
    script_statistics=scripts.find_next_sibling().text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-05-15 16:05:15:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-16 14:53:09:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-16 15:11:47:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-16 17:29:44:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-05-18 14:44:39:
Traceback (most recent call last):
  File "/home/oliver/toutiao_workspace/toutiaohaoWorking/writer_fetch.py", line 50, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-12-07 16:43:36:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:43:37:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:43:46:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:43:46:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:43:58:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:43:58:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:48:46:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:49:07:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:49:09:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:49:17:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:49:17:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:51:14:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 16:58:17:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 18:07:49:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 18:09:28:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 18:10:08:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 18:10:41:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 38, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 18:19:47:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 39, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:20:35:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 39, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'NoneType' object has no attribute 'text'
------------------------------------------

2017-12-07 18:22:05:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 39, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:23:09:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 39, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:24:16:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 39, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:26:07:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 39, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:26:43:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 40, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:29:13:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 41, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:30:32:
Traceback (most recent call last):
  File "/mnt/hgfs/SharedSpace/toutiaohao/writer_fetch.py", line 41, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:38:44:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 43, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:41:20:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 36, in fetchWriterTitle
    if res_html.status_code==200:
AttributeError: 'NoneType' object has no attribute 'status_code'
------------------------------------------

2017-12-07 18:42:03:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 37, in fetchWriterTitle
    if res_html.status_code==200:
AttributeError: 'NoneType' object has no attribute 'status_code'
------------------------------------------

2017-12-07 18:43:07:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 40, in fetchWriterTitle
    html=res_html.page_source
AttributeError: 'NoneType' object has no attribute 'page_source'
------------------------------------------

2017-12-07 18:44:46:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 47, in fetchWriterTitle
    script_heads=scripts.text.replace('\n','').replace(' ','').split(';')
AttributeError: 'list' object has no attribute 'text'
------------------------------------------

2017-12-07 18:45:31:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 59, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-12-07 18:47:22:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 59, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-12-07 18:48:01:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 58, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-12-07 18:49:42:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 59, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-12-07 18:51:36:
Traceback (most recent call last):
  File "C:\SharedSpace\toutiaohao\writer_fetch.py", line 60, in fetchWriterTitle
    avtar_img=head.split(':')[1]+':'+head.split(':')[2]
IndexError: list index out of range
------------------------------------------

2017-12-21 15:35:06:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 33, in fetchWriterTitle
    res=urllib.request.urlopen(req)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
------------------------------------------

2017-12-21 15:35:10:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 33, in fetchWriterTitle
    res=urllib.request.urlopen(req)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
------------------------------------------

2017-12-21 15:40:31:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 33, in fetchWriterTitle
    res=urllib.request.urlopen(req)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
------------------------------------------

2017-12-21 15:40:34:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 33, in fetchWriterTitle
    res=urllib.request.urlopen(req)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
------------------------------------------

2017-12-21 15:40:38:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 33, in fetchWriterTitle
    res=urllib.request.urlopen(req)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\MyUtils\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: FORBIDDEN
------------------------------------------

2017-12-21 15:49:22:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 42, in fetchWriterTitle
    html=driver.page_source()
TypeError: 'str' object is not callable
------------------------------------------

2017-12-21 15:50:59:
Traceback (most recent call last):
  File "c:\SharedSpace\toutiaohao\writer_fetch.py", line 42, in fetchWriterTitle
    html=driver.page_source()
TypeError: 'str' object is not callable
------------------------------------------

